

CREATE TABLE Library_Branch (
	BranchID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BranchName nvarchar(50) NOT NULL,
	Address nvarchar(100) NOT NULL
);

CREATE TABLE Book_Loans (
	BookID INT NOT NULL CONSTRAINT fk_BookID FOREIGN KEY REFERENCES Books(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT NOT NULL CONSTRAINT fk_BranchID FOREIGN KEY REFERENCES Library_Branch(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	CardNo nvarchar(50) NOT NULL CONSTRAINT fk_CardNo FOREIGN KEY REFERENCES Borrower(CardNo) ON UPDATE CASCADE ON DELETE CASCADE,
	DateOut nvarchar(50) NOT NULL,
	DateDue nvarchar(50) NOT NULL
);

CREATE TABLE Borrower (
	CardNo nvarchar(50) PRIMARY KEY NOT NULL,
	Name nvarchar(50) NOT NULL,
	Address nvarchar(100) NOT NULL,
	Phone nvarchar(50) NOT NULL
);

CREATE TABLE Books (
	BookID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Title nvarchar(50) NOT NULL,
	PublisherName nvarchar(50) NOT NULL CONSTRAINT fk_PublisherName FOREIGN KEY REFERENCES Publisher(PublisherName) ON UPDATE CASCADE ON DELETE CASCADE,
);

CREATE TABLE Book_Authors (
	BookID INT NOT NULL CONSTRAINT fk2_BookID FOREIGN KEY REFERENCES Books(BookId) ON UPDATE CASCADE ON DELETE CASCADE,
	AuthorName nvarchar(50) NOT NULL
);

CREATE TABLE Book_Copies (
	BookID INT NOT NULL CONSTRAINT fk3_BookID FOREIGN KEY REFERENCES Books(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT NOT NULL CONSTRAINT fk2_BranchID FOREIGN KEY REFERENCES Library_Branch(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	Number_Of_Copies INT NOT NULL
);

CREATE TABLE Publisher (
	PublisherName nvarchar(50) PRIMARY KEY NOT NULL,
	Address nvarchar(100) NOT NULL,
	Phone nvarchar(50) NOT NULL
);